
project_id = "hagweqrpbrjbtsbbscbn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://zapagent-ai.lovable.site"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_confirmations = false
enable_manual_linking = false
# Configuração correta do OTP
otp_expiry = 3600
otp_length = 6
# Configuração correta da proteção de senhas vazadas
enable_leaked_password_protection = false

[edge_functions]
enabled = true

[functions.create-checkout]
verify_jwt = false

[functions.verify-subscription]
verify_jwt = true
