
project_id = "hagweqrpbrjbtsbbscbn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://zapagent-ai.lovable.site"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10

[edge_functions]
enabled = true

[functions.create-checkout]
verify_jwt = false

[functions.verify-subscription]
verify_jwt = true
